[[news]]
date = "2026-03"
content = "Current work on a new framework for Diffusion RL under progress!!! Aiming for NeurIPS 2026 🚀."

[[news]]
date = "2026-01"
content = "🎉🎉 I2E, my first collaborative work with fellows from Tsinghua University and Shanghai AI Lab, has been submitted to ACL 2026!"
